[accounts.mailbox]
email = "julioribeiro@mailbox.org"
display-name = "Julio Ribeiro"
default = true

# IMAP — reading
backend.type = "imap"
backend.host = "imap.mailbox.org"
backend.port = 993
backend.encryption.type = "tls"
backend.login = "julioribeiro@mailbox.org"
backend.auth.type = "password"
backend.auth.cmd = "security find-internet-password -s imap.mailbox.org -a julioribeiro@mailbox.org -w"

# SMTP — sending
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.mailbox.org"
message.send.backend.port = 587
message.send.backend.encryption.type = "start-tls"
message.send.backend.login = "julioribeiro@mailbox.org"
message.send.backend.auth.type = "password"
message.send.backend.auth.cmd = "security find-internet-password -s imap.mailbox.org -a julioribeiro@mailbox.org -w"
